### ISSUE TITLE
Issue with koha 21.11.05

### ISSUE THREAD

**Issue by hagud** [bywatersolutions/koha-plugin-coverflow#53] opened 2022-04-29 10:43 UTC
Good morning 

I have just installed 21.11.05 and plugin is not working there is a 500 error

specifically 

{"error":"Unhandled exception (Can't use string (\"select b.title as title, bi.bibl\"...) as a HASH ref while \"strict refs\" in use at \/usr\/share\/koha\/lib\/C4\/Reports\/Guided.pm line 559.\n)"}

I think Guided.pm code has been edited, becuase this plugin was working fine with koha 21.11.4

thans a lot

**Comment by ioschlies1** [comment] 2022-05-02 15:41
Hi. I would like to report the same issue. Is there some workaround while the problem is not fixed yet?
Thank you.

**Comment by kidclamp** [comment] 2022-05-03 11:01
Caused by https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=26669

**Comment by tomascohen** [comment] 2022-08-17 17:17
Should this be marked as solved then?

**Comment by ioschlies1** [comment] 2022-08-17 18:32
For me personally it is solved.

**Comment by kidclamp** [comment] 2022-08-17 18:34
Solved by 0d4c92c7602e0922dc5e2aeba06e423c9a50bede

**Closed by kidclamp** 2022-08-17 18:34 UTC
